### ISSUE TITLE
Change 'tool_options' to 'tool-options' in tools branch

### ISSUE THREAD

**Issue by ptcNOP** [MITRECND/cuckoo#16]

**Comment by depaolism** [comment]
I was considering changing this when I was committing the code for changing 'tool_dir' to 'tool-dir', so I'm not against the change. I didn't know what the proper format should be for this though since it isn't a flag.

We could also change 'tool_options' to just 'tool' since it is under the '--options' flag already, but this could lead to confusion on how to properly use the tool.

Any changes to 'tool_options' would also be made to 'sample_options'.
